# TODO
# fireshot
# google-chrome
packages_to_install:
  - arandr
  - bluez
  - bluez-tools
  - curl
  - fasd
  - git
  - htop
  - inotify-tools
  - shellcheck
  - tmux
  - tree
  - vim
  - wget

snaps_to_install:
  # - { snap: spotify }
  - { snap: hub, classic: yes }
